=== zherar7ordoya/LUG/(FINAL)/(Prinzo) EjemplosXML_v3/UI_XML/Direcciones.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Enter you external DTD here -->
<!ELEMENT Direcciones (Direccion*)>
<!ELEMENT Direccion (Nombre, Empresa, Movil)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Empresa (#PCDATA)>
<!ELEMENT Movil (#PCDATA)>

=== zherar7ordoya/LUG/(FINAL)/(Prinzo) EjemplosXML_v3/UI_XML/PruebaDTDExterna.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Direcciones SYSTEM "Direcciones.dtd">

<Direcciones>

	<Direccion>
		<Nombre>Juan Fernandez</Nombre>
		<Empresa>Pept S.A.</Empresa>
		<Movil>(015) 555-8546</Movil>
	</Direccion>

	<Direccion>
		<Nombre>Fernando Kilua</Nombre>
		<Empresa>Demosc S.R.L.</Empresa>
		<Movil>(011) 555-6548</Movil>
	</Direccion>

	<Direccion>
		<Nombre>Elisa Gonz√°les</Nombre>
		<Empresa>Sanatoria del Rosario S.A.</Empresa>
		<Movil>(549) 555-2564</Movil>
	</Direccion>

</Direcciones>
